# Generated by Django 4.2.5 on 2023-10-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=25, verbose_name='Detalle')),
                ('num_factura', models.BigIntegerField(verbose_name='Numero de Factura')),
                ('agregado', models.DateField(verbose_name='Agregado en')),
            ],
        ),
    ]
